### PR TITLE
add rotationspeed for humidifier

### PR DESCRIPTION
**Pull request by akaminsky-net**
Hi, @0x5e. I added also [rotationspeed](https://developers.homebridge.io/#/service/HumidifierDehumidifier) support for humidifier intensivity. First I did it as characteristic of HumidifierDehumidifier device, but these changes were reflected only in homebridge GUI, but no any new controls in homebridge app (tested on iOS 16.1.1).

Then I decided to add Fan Service to Humidifier and it worked fine in home app UI.

### CODE REVIEW

**Comment by 0x5e** [comment]
Did you tried restart the homekit app, or clear accessory cache? Sometimes services and characteristic just not updated, I don't know why too. If it is the cache issue, add rotationspeed into Humidifier can be better so they are still the same single device in the homekit.
If rotationspeed on Humidifier really not working, I think we should submit a issue to homebridge too.

I will add a virtual Humidifier and test later.

**Comment by akaminsky-net** [comment]
Yep, I tried, but no luck. I commented new device creation and pushed to the branch. Probably virtual device will work fine, I don't know)

**Comment by 0x5e** [comment]
I confirmed with no luck too. I see homebridge-miot is still using `HumidifierDehumidifier` with `RotationSpeed` and don't know why. https://github.com/merdok/homebridge-miot/blob/45908dd01dd77991a5c4e27ac43c2886766b068b/lib/modules/humidifier/HumidifierAccessory.js#L84

OK we just using Fan instead, if the issue can be solved then we change back.


Back to the code, I see documentation:
https://developer.tuya.com/cn/docs/iot/f?id=K9gf46h2s6dzm
```
speed | 风速档位 | Enum | {“range”:[“1”,“2”,“3”,“4”,“5”,“6”]}
```

You are using `mode` instead of `speed`, is it a mistake?
And, although the document says the range is the string of 1-6, but still different device will have special values such as `["level_1", "level_2", "level_3", "level_4"]` or `["low", "meduim", "high"]`. So I suggest we can ignore the value of the string, and remap the range index to the 0%-100%, like `FanAccessory.configureRotationSpeedLevel()` does.

Currently I haven't figure out how to better reuse the initial code of Characteristic, sorry for the inconvience, maybe just copy and paste.

**Comment by akaminsky-net** [comment]
Your link is pointing to another device (Air Purifier), humidifier don't have such attribute - https://developer.tuya.com/en/docs/iot/f?id=K9gf45rjel6x5 
Regarding mode and level values remap, according to link above it's range of these values:
`{“range”:[“large”,“middle”,“small”,“interval”,“continuous”]}`
I don't know how to map correctly last 2 values.
Moreover my humidifier even don't have these modes.

```
[
  {
    "active_time": 1668935508,
    "biz_type": 18,
    "category": "jsq",
    "create_time": 1668531085,
    "icon": "smart/icon/bay1620727285254Vlxq/5972246d92ff8c8af68257556b5233b9.jpg",
    "id": "<edit>",
    "ip": "<edit>",
    "lat": "",
    "local_key": "<edit>",
    "lon": "",
    "model": "4076S 另一名",
    "name": "Humidifier",
    "online": true,
    "owner_id": "<edit>",
    "product_id": "<edit>",
    "product_name": "Humidifier",
    "status": [
      {
        "code": "switch",
        "value": true
      },
      {
        "code": "switch_spray",
        "value": false
      },
      {
        "code": "mode",
        "value": "small"
      },
      {
        "code": "switch_led",
        "value": true
      },
      {
        "code": "temp_current",
        "value": 24
      },
      {
        "code": "humidity_set",
        "value": 40
      },
      {
        "code": "humidity_current",
        "value": 40
      }
    ],
    "sub": false,
    "time_zone": "+03:00",
    "uid": "<edit>",
    "update_time": 1668935508,
    "uuid": "<edit>",
    "schema": [
      {
        "code": "switch",
        "mode": "rw",
        "type": "Boolean",
        "values": "{}",
        "property": {}
      },
      {
        "code": "switch_spray",
        "mode": "rw",
        "type": "Boolean",
        "values": "{}",
        "property": {}
      },
      {
        "code": "mode",
        "mode": "rw",
        "type": "Enum",
        "values": "{\"range\":[\"large\",\"middle\",\"small\"]}",
        "property": {
          "range": [
            "large",
            "middle",
            "small"
          ]
        }
      },
      {
        "code": "switch_led",
        "mode": "rw",
        "type": "Boolean",
        "values": "{}",
        "property": {}
      },
      {
        "code": "humidity_set",
        "mode": "rw",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":\"40\",\"max\":\"90\",\"scale\":\"0\",\"step\":\"5\"}",
        "property": {
          "unit": "%",
          "min": "40",
          "max": "90",
          "scale": "0",
          "step": "5"
        }
      },
      {
        "code": "temp_current",
        "mode": "ro",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":\"0\",\"max\":\"50\",\"scale\":\"0\",\"step\":\"1\"}",
        "property": {
          "unit": "℃",
          "min": "0",
          "max": "50",
          "scale": "0",
          "step": "1"
        }
      },
      {
        "code": "humidity_current",
        "mode": "ro",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":\"0\",\"max\":\"100\",\"scale\":\"0\",\"step\":\"1\"}",
        "property": {
          "unit": "%",
          "min": "0",
          "max": "100",
          "scale": "0",
          "step": "1"
        }
      }
    ]
  }
]
```

**Comment by 0x5e** [comment]
Oh sorry for my mistake. If the code is a mode, not the enum levels, the current code should be okay.
Thanks for the PR :)

**Review by 0x5e — APPROVED** [review]

**Comment by akaminsky-net** [comment]
You're welcome, thank you for your efforts ! Current code version still doesn't work with Apple Home :) Should I create separate bug ?

**Comment by 0x5e** [comment]
> You're welcome, thank you for your efforts ! Current code version still doesn't work with Apple Home :) Should I create separate bug ?

What does that mean? I'm not clearly understand.

**Comment by akaminsky-net** [comment]
Sorry, my English isn’t so good :) I mean merged code version doesn’t create new fan accessor. It’s using internal rotationSpeed characteristic instead. As we already know this control is absent in Home App. I don’t know which option is better:
- Current (merged) version implemented as it should be by design, but it doesn’t work in Apple home app. Probably Apple will fix it (haha).
- implement as sub-accessory. Then we can see speed control in app (first commit  from this PR).

**Comment by 0x5e** [comment]
Use the fan accessory is okay, in my local I just uncomment the fan service code which you have commented. I will commit.
English is not my native language too :)

Is that okay?
https://github.com/0x5e/homebridge-tuya-platform/commit/7366e60444cc297a938bb7d29c5aa52bf83bcc71

And I update the way of output logs, `this.log` will have prefix of the device name now.

**Comment by akaminsky-net** [comment]
Yep, this one is fine. Thank you again :)

**Comment by 0x5e** [comment]
@akaminsky-net  Actually I found `RotationSpeed` works with `Humidifier`, it appears in the setting page, not like fan speed and lightbulb brightness. And also works in `Dehumidifier`.

image

**Comment by akaminsky-net** [comment]
Hi, @0x5e.
Great! Then we for sure can comment creating new accessory and use single accessory instead. 
Please let me know If I can help you.

**Comment by 0x5e** [comment]
I will fix this today, it' okay :)

**Comment by akaminsky-net** [comment]
Checked fresh build (1.7.0.beta.4), works fine, thanks! Not so easy to change as previously, because we can change it in settings page of **sub**accessory, not accessory. Please have a look at the attached video. Probably we can find a way to move it from subaccessory settings to accessory ?

https://user-images.githubusercontent.com/8268609/206718506-f769dd94-2732-44d4-b0ca-d2d4a6894b75.MP4

**Comment by 0x5e** [comment]
I tried to move temperature into Humidifier service but it won't work. For the light accessories there's an option to split one accessory into multiple accessory,  But I don't know thy Humidifier with TemperatureSensor didn't show this...

IMG_8420
IMG_8421

**Comment by 0x5e** [comment]
It's a common issue, dehumidifier are the same too. I think maybe Apple's logic is only when each accessory have the control panel, then it's allowed to split. The Sensors won't appeared in the accessory list individually by design.

**Comment by akaminsky-net** [comment]
Ok,  probably leave "as is" is good solution. Sorry for disturbance :))

**Pull request merged**
