### PR TITLE
Update ThermostatAccessory.ts

### PR DESCRIPTION
**Pull request by DominoLeChat**

### CODE REVIEW

**Comment by 0x5e** [comment]
10-38 is the max range of the homekit, property.min-property.max is the device range, which can't be larger than 10-38, otherwise there will be an error.

Can you describle the reason to switching 10 and 38?

**Comment by DominoLeChat** [comment]
Hi,
First of all, I'm not a developer and I don't know how to use GitHub other than downloading stuff :-D
I tried to configure your plugin on my HomeBridge instance, but the Thermostat accessory crashes my HB instance with the following error : 

 
Error: Error setting CharacteristicsProps for 'Target Temperature': 'minValue' cannot be greater or equal the 'maxValue'!
    at TargetTemperature.Characteristic.setProps (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1221:15)
    at ThermostatAccessory.configureTargetTemp (/volume1/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/ThermostatAccessory.ts:223:8)
    at new ThermostatAccessory (/volume1/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/ThermostatAccessory.ts:13:10)
    at Function.createAccessory (/volume1/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AccessoryFactory.ts:78:19)
    at TuyaPlatform.addAccessory (/volume1/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:305:40)
    at TuyaPlatform.initDevices (/volume1/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:116:12)
    at HomebridgeAPI.<anonymous> (/volume1/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:71:7)

**Comment by 0x5e** [comment]
It's okay, could you please upload your device infos? Please see the troubleshooting section in readme, let me fix it.

**Comment by DominoLeChat** [comment]
Thank you very much ! I removed some of the sensitive data, but didn't remove the model name, it was already empty in the file.

[TuyaDeviceList.eu1609092985368A5RKI.json.txt](https://github.com/0x5e/homebridge-tuya-platform/files/9996842/TuyaDeviceList.eu1609092985368A5RKI.json.txt)

  {
    "active_time": 1668280252,
    "biz_type": 18,
    "category": "wk",
    "create_time": 1571062992,
    "icon": "smart/icon/15264583415nnlzwfs1qd2wqz6i937op3nmi_0.png",
    "id": "366034752cf4325ed723",
    "ip": "**.**.****.*",
    "lat": "**.****",
    "local_key": "****************",
    "lon": "*.****",
    "model": "",
    "name": "Thermostat",
    "online": true,
    "owner_id": "22604346",
    "product_id": "IAYz2WK1th0cMLmL",
    "product_name": "thermostat",
    "status": [
      {
        "code": "switch",
        "value": true
      },
      {
        "code": "temp_set",
        "value": 60
      },
      {
        "code": "upper_temp",
        "value": 47
      },
      {
        "code": "eco",
        "value": false
      },
      {
        "code": "child_lock",
        "value": false
      }
    ],
    "sub": false,
    "time_zone": "+01:00",
    "uid": "eu1609092985368A5RKI",
    "update_time": 1668281003,
    "uuid": "366034752cf4325ed723",
    "schema": [
      {
        "code": "eco",
        "mode": "rw",
        "type": "Boolean",
        "values": "{}",
        "property": {}
      },
      {
        "code": "temp_set",
        "mode": "rw",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":10,\"max\":70,\"scale\":1,\"step\":5}",
        "property": {
          "unit": "℃",
          "min": 10,
          "max": 70,
          "scale": 1,
          "step": 5
        }
      },
      {
        "code": "switch",
        "mode": "rw",
        "type": "Boolean",
        "values": "{}",
        "property": {}
      },
      {
        "code": "child_lock",
        "mode": "rw",
        "type": "Boolean",
        "values": "{}",
        "property": {}
      },
      {
        "code": "upper_temp",
        "mode": "rw",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":5}",
        "property": {
          "unit": "℃",
          "min": 0,
          "max": 100,
          "scale": 0,
          "step": 5
        }
      }
    ]
  }

**Comment by 0x5e** [comment]
```json
{
"code": "temp_set",
"mode": "rw",
"type": "Integer",
"property": {
  "unit": "℃",
  "min": 10,
  "max": 70,
  "scale": 1,
  "step": 5
}
```

I think your device may have a wrong target temperature property. `scale=1` means your device's temperature range should be divided by `10^1`, then is `1℃~7℃`. Actuall is it `10℃~70℃`?

**Comment by 0x5e** [comment]
Moved to #72

**Pull request closed without merging**
