### PR TITLE
Reimplemented FanAccessory; Add Ceiling Fan Light support (fsd).

### PR DESCRIPTION
**Pull request by 0x5e**
tuya/tuya-homebridge#300 and tuya/tuya-homebridge#295 should fixed, please have a try.

### CODE REVIEW

**Comment by 0x5e** [comment]
Ceiling Fan Light is supported now in 1.6.0-beta.18. Since `FanAccessory` has beem reimplemented please tell me if it's not working well, thanks. @fercho2903 @iGageit

**Comment by iGageit** [comment]
Oh Wow! it works now! Thank you so much!
hey, I make videos on social media and would like to give you a shoutout for your incredible development skills. Any code projects you would like people to know about? :) @0x5e

**Comment by 0x5e** [comment]
> Oh Wow! it works now! Thank you so much!
> 
> hey, I make videos on social media and would like to give you a shoutout for your incredible development skills. Any code projects you would like people to know about? :) @0x5e 

Thanks, actually my other projects are old or small which may not useful for others. Homebridge Tuya is the first one I would like to share maybe.
I just like open source community and because work at tuya before, so I have experience to do this to share with :)

**Comment by 0x5e** [comment]
Also tuya#313

**Comment by ryanuy** [comment]
@0x5e Im trying to added the fan light switch into homekit but only the fan is appearing. using 1.6.0-beta.25, is it removed on this build?

**Comment by 0x5e** [comment]
@ryanuy have you used previous beta version before? Does it work?
Please following the readme troubleshooting section and upload the TuyaDeviceList.json, thanks.

**Comment by ryanuy** [comment]
> @ryanuy have you used previous beta version before? Does it work?
Please following the readme troubleshooting section and upload the TuyaDeviceList.json, thanks.

@0x5e , this is the first time I'm using your beta.. please see the file below. thank you.
[TuyaDeviceList.json.txt](https://github.com/0x5e/homebridge-tuya-platform/files/9945892/TuyaDeviceList.json.txt)

**Comment by 0x5e** [comment]
From your file I can only see `switch` for fan switch and `fan_speed` for fan speed, I didn't see anything for lights. Are you sure your device support light? Can you take some photos on Tuya Platform -> Cloud Develop -> device debugging page of your devices? Take photos for the standard instruction set and standard status set.
@ryanuy

**Comment by ryanuy** [comment]
> From your file I can only see `switch` for fan switch and `fan_speed` for fan speed, I didn't see anything for lights. Are you sure your device support light? Can you take some photos on Tuya Platform -> Cloud Develop -> device debugging page of your devices? Take photos for the standard instruction set and standard status set. @ryanuy

@0x5e  I check the Tuya IOT Platform and it looks like Tuya platform is not sending all the device info to the Tuya IOT Platform.

tuya_fan_light_switch

but on the tuya smart app it has both fan controls and light switch.

Tuya Smart App

**Comment by 0x5e** [comment]
@ryanuy So, unfortunately your device have non-standard instrument set which are invisible from tuya platform, and we can't get it from OpenAPI too...
https://github.com/0x5e/homebridge-tuya-platform/issues/44#issuecomment-1305353363

**Comment by ryanuy** [comment]
> 

I looks that way. thank you for you help.

**Comment by 0x5e** [comment]
You are welcome

**Pull request merged**
