### PR TITLE
Add support for 'mal' type as SecuritySystem

### PR DESCRIPTION
**Pull request by bFollon**
This PR adds support to the 'mal' type as securitySystem.

It implements the `SecuritySystemCurrentState` and the `SecuritySystemTargetState` characteristics.

The SecuritySystemCurrentState has to check the sos_state in case it is `true` to return `ALARM_TRIGGERED`.

I've also implemented that disarming the alarm from the home app during an alarm activation allows you to stop the alarm itself.

`tuyaHomebridgeMap` is a map that allows me to "translate" codes from tuya to its equivalent in Homebridge.
If there is a better place for that code please let me know.

All feedback is very welcome and appreciated.

### CODE REVIEW

**Comment by 0x5e** [comment]
Thanks! I will see it when i'm back to home.

**Comment by bFollon** [comment]
As you can see, I’ve had to make some tweaks to support the night mode that the Home app offers.

I think that what the home app offers can be edited. I’ll take a look into that when I get the chance.

**Comment by 0x5e** [comment]
these two characteristics are only used by single service `SecuritySystem`, I think it's okay to put them in the SecuritySystemAccessory. or you can put them together into `./characteristics/SecuritySystemState.ts` like `./characteristics/RotationSpeed.ts`, also okay.

I'm not familiar with `SecuritySystem` and don't have test environment, as long as the duplicate map get removed and works on your device I will merge it. thanks for the contribution :)

**Comment by bFollon** [comment]
Thank you for your input @0x5e !
I've unified SecuritySystemCurrentState and SecuritySystemTargetState into SecuritySystemState as you suggested so we don't have the map duplicated anymore.

I've been testing it with a Security System I have around and it works great.
Also, since you mentioned you don't have a test environment, I've also used virtual devices on tuya for testing.

**Comment by bFollon** [comment]
An thank **you** for maintaining this plugin! :)

**Review by 0x5e — APPROVED** [review]

**Comment by 0x5e** [comment]
thanks for the contribution again!

**Pull request merged**
