### PR TITLE
Add initial Camera support (`sp`).

### PR DESCRIPTION
**Pull request by 0x5e**
Initial support with floodlight, motion detect, doorbell, and some switch buttons.

### CODE REVIEW

**Comment by erikbdev** [comment]
Nice! I will be forking this soon and add support for cameras and doorbells!

**Comment by 0x5e** [comment]
Thanks @ErrorErrorError !

The doorbell is included in this pr, but I'm not sure if we need the `doorbell_pic`. I guess if a camera doorbell contains `doorbell_pic`, it will always have `doorbell_ring_exist`? We can get the picture from `doorbell_pic` but maybe not useful... What do you think about it?

And we can split the pulsar and camera stream into the later PR, once the doorbell and motion event is done, I can publish a beta version for users to try.

**Comment by erikbdev** [comment]
some doorbells use doorbell_pic or alert_message to notify when the doorbell was rang. We need it to notify when the data stored in the state changes.

**Comment by 0x5e** [comment]
@ErrorErrorError Do you know the type and value of `alert_message`? This can't be found in the document.
And `movement_detect_pic` I tested is also a single event without `motion event end` notify, so if I use the `MotionSensor`, I need to set a default timeout to off the `MotionDetected`. What do you think about this?

**Comment by erikbdev** [comment]
> @ErrorErrorError Do you know the type and value of `alert_message`? This can't be found in the document.
> 
> And `movement_detect_pic` I tested is also a single event without `motion event end` notify, so if I use the `MotionSensor`, I need to set a default timeout to off the `MotionDetected`. What do you think about this?

Yeah most, if not all of the event notifications are single event, meaning they don't notify when there is no motion available. We will need to set a timeout that turns off MotionSensor.

In regards to alert_message, someone on scrypted under Tuya channel has that status info, which is how I found out about it.

**Pull request merged**
