### PR TITLE
Add some more values for work_state parameter

### PR DESCRIPTION
**Pull request by burcadoruciprian**
Hello
I have a Tuya thermostat which has PNI CT36 (quite popular here in Romania) which has some peculiar values for work_state parameter. Hope you will allow this MR

Thanks

### CODE REVIEW

**Comment by 0x5e** [comment]
Hi @burcadoruciprian , I see the code `hot` appears at many places, not only `CurrentHeatingCoolingState` but also `TargetHeatingCoolingState`. Shall we add `heating` in `TargetHeatingCoolingState`?

**Comment by burcadoruciprian** [comment]
@0x5e No these values apply only to "work_state" parameter. The other two use "mode" parameter (which do not match at all, but this is another story altogether) 

{
    "code": "mode",
    "desc": "{\"range\":[\"manual\",\"eco\",\"program\"]}",
    "name": "工作模式",
    "type": "Enum",
    "values": "{\"range\":[\"manual\",\"eco\",\"program\"]}"
  },
  {
    "code": "work_state",
    "name": "状态",
    "type": "Enum",
    "values": "{\"range\":[\"idle\",\"heating\",\"window_opened\"]}"
  },

**Comment by 0x5e** [comment]
OK, thanks for the PR!

**Comment by burcadoruciprian** [comment]
@0x5e cheers

**Pull request merged**
