### PR TITLE
Add smart lock support.

### LINKED ISSUE #221: Add support for Lock Mechanism
Any plans to include an integration for Lock mechanism?

### PR DESCRIPTION
**Pull request by 0x5e**
Need user to test.

### CODE REVIEW

**Comment by pfgimutao** [comment]
Hi I was able to create a working lock accessory that utilizes the smart lock open service APIs. Can you include this in your code? I have tested  this using a jtmspro device which is a retrofit smart door lock that uses bluetooth. Here is my fork of your code. https://github.com/pfgimutao/homebridge-tuya-platform-lock

**Comment by 0x5e** [comment]
@pfgimutao thanks! I will merge it soon.

**Comment by 0x5e** [comment]
@pfgimutao released in 1.7.0-beta.29. if it's not working please let me know.

**Comment by pfgimutao** [comment]
@0x5e thanks for the merge. I've tested it and it is working for me. By any chance, do you have any support for wnykq?

**Comment by 0x5e** [comment]
> @0x5e thanks for the merge. I've tested it and it is working for me. By any chance, do you have any support for wnykq? 

wnkyq is supported now, but only for IR device, RF device not supported by cloud api.

**Comment by felipehjcosta** [comment]
@0x5e 

I've tested here and its workin now! Thank you very much!

**Comment by felipehjcosta** [comment]
@0x5e 

I've tested here and its workin now! 

I would like to share that I have been trying to use this smart lock  via my Zemismart HomeKit Hub but it never have worked... It only shows the smart lock status open or close on HomeKit. Now, I can control it and check battery level as well!

Thank you very much!

**Comment by gonzaechev** [comment]
Hello, I have the zigbee version with Zemismart Hub and another with Wifi chip (Product Category
ms) This plugin work with wifi version? I added to homebridge, this is the result:

[19/03/2023, 13:31:27] [@0x5e/homebridge-tuya-platform] [Acceso] Product Category: ms
[19/03/2023, 13:31:27] [@0x5e/homebridge-tuya-platform] [Acceso] Missing one of the required schema: [ 'lock_motor_state' ]
[19/03/2023, 13:31:27] [@0x5e/homebridge-tuya-platform] [Acceso] Please switch device control mode to "DP Insctrution", and set `deviceOverrides` manually.
[19/03/2023, 13:31:27] [@0x5e/homebridge-tuya-platform] [Acceso] Detail information: https://github.com/0x5e/homebridge-tuya-platform#faq
[19/03/2023, 13:31:27] [@0x5e/homebridge-tuya-platform] [Acceso] Existing schema: [
  {
    code: 'alarm_lock',
    mode: 'ro',
    type: 'Enum',
    property: {
      range: [
        'wrong_finger',  'wrong_password',
        'wrong_card',    'wrong_face',
        'tongue_bad',    'too_hot',
        'unclosed_time', 'tongue_not_out',
        'pry',           'key_in',
        'low_battery',   'power_off',
        'shock',         [length]: 13
      ]
    }
  },
  {
    code: 'battery_state',
    mode: 'ro',
    type: 'Enum',
    property: { range: [ 'high', 'medium', 'low', 'poweroff', [length]: 4 ] }
  },
  { code: 'doorbell', mode: 'ro', type: 'Boolean', property: {} },
  { code: 'hijack', mode: 'ro', type: 'Boolean', property: {} },
  {
    code: 'reply_unlock_request',
    mode: 'wo',
    type: 'Boolean',
    property: {}
  },
  {
    code: 'unlock_app',
    mode: 'ro',
    type: 'Integer',
    property: { min: 0, max: 999, scale: 0, step: 1 }
  },
  {
    code: 'unlock_card',
    mode: 'ro',
    type: 'Integer',
    property: { min: 0, max: 999, scale: 0, step: 1 }
  },
  {
    code: 'unlock_dynamic',
    mode: 'ro',
    type: 'Integer',
    property: { min: 0, max: 999, scale: 0, step: 1 }
  },
  {
    code: 'unlock_fingerprint',
    mode: 'ro',
    type: 'Integer',
    property: { min: 0, max: 999, scale: 0, step: 1 }
  },
  {
    code: 'unlock_password',
    mode: 'ro',
    type: 'Integer',
    property: { min: 0, max: 999, scale: 0, step: 1 }
  },
  {
    code: 'unlock_request',
    mode: 'ro',
    type: 'Integer',
    property: { min: 0, max: 90, scale: 0, step: 1 }
  },
  {
    code: 'unlock_temporary',
    mode: 'ro',
    type: 'Integer',
    property: { min: 0, max: 999, scale: 0, step: 1 }
  },
  [length]: 12

**Comment by 0x5e** [comment]
@gonzaechev please refer to readme, change device control mode and test if it solves your problem?

**Comment by nevirous** [comment]
> @gonzaechev please refer to readme, change device control mode and test if it solves your problem?

hey, i already change to DP Mode, and overrides the device via plugin but it didn't solve the problem, can you help me with this?

**Pull request merged**
