### PR TITLE
Added support to 2ch windows covering

### PR DESCRIPTION
**Pull request by CryptoIR**
Added supoprt to Tuya 2ch windows blinds

### CODE REVIEW

**Comment by CryptoIR** [comment]
@0x5e

**Comment by 0x5e** [comment]
@CryptoIR Thanks! I'm not at home, I will review them when I have computer :)

**Comment by 0x5e** [comment]
LGTM, thanks @CryptoIR again!

**Comment by xrust83** [comment]
Well done guys, now all my single-channel curtains show two channels =). If I'm not the only one, let me know

How can I get rid of this luxury? The number of my smart curtains doubled for free =)

image
image
image
image
image

**Comment by zero1niner** [comment]
Ah! I think this is exactly what I need. Can anyone explain how I can apply this solution to get my 2ch NHZS curtain controller to show both channels? Thanks for the help!

**Pull request merged**
